package com.ticketbus.common.domain;

public enum AuditAction {
    TICKET_PURCHASED,
    TICKET_VALIDATED,
    TICKET_REVOKED,
    PAYMENT_INITIATED,
    PAYMENT_REFUNDED,
    WALLET_TOPUP,
    WALLET_DEBIT,
    FRAUD_ALERT_CREATED,
    FRAUD_ALERT_RESOLVED,
    USER_CREATED,
    USER_UPDATED,
    PRODUCT_CREATED,
    OPERATOR_CREATED,
    ZONE_CREATED
}

